# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
      include:
      - master
  paths:
    include:
    - backend

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image

  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'docker login -u "$(DHA)" -p "$(DHP)" docker.io'
    - task: Docker@2
      inputs:
        containerRegistry: 'Psicoapp docker hub'
        repository: 'psicoapp/backpsicoapp'
        command: 'buildAndPush'
        Dockerfile: './backend/backpsicoapp.dockerfile'
