@host = http://localhost:4000/

###
#todos los casos
GET {{host}}case/filter/0 
###
#Edad ascendente
GET {{host}}case/filter/1/1
###
#Edad descendente
GET {{host}}case/filter/1/2
###
#Fecha de creacion ascendente
GET {{host}}case/filter/2/1
###
#Fecha de creacion descendente
GET {{host}}case/filter/2/2
###
#Pendientes de asignar
GET {{host}}case/filter/3
###
#desistidos
GET {{host}}case/filter/4

###
# Obtiene los registros por consulta aleatoria, nombre o id
# el filtro está unicamente por id o por numero de caso
GET {{host}}cases/byfilter?filter=2020

