@host = http://localhost:4000

###
POST {{host}}/diagnostic/create/uuid6
Content-Type: application/json

{
    "uuidDSM5":"T001",
    "descriptionOfProblem":"Este es el texto asociado al archivo",
    "descriptionOfProblemFile":"Y esto es el archivo"
}

###
GET {{host}}/diagnostic/get
Content-Type: application/json

###
GET {{host}}/diagnostic/getdsm
Content-Type: application/json
