@host = http://138.197.215.60:4000
# Hace un post a la tabla PAC_Case
POST {{host}}case/create
Content-Type: application/json

{
    "uuidAssignedUser": "uuid4",
    "uuidOwnerUser" : "uuid5",
    "uuidPersonPatient": "uuid3",
    "uuidStage": "stage1",
    "reasonForConsultation": "hola desde back"
}

###
#Hace una actualización a la tabla en base al uuid
PUT {{host}}case/update/uuidcase3
Content-Type: application/json

{
    "uuidAssignedUser": "uuid7",
    "uuidOwnerUser" : "uuid5",
    "uuidPersonPatient": "uuid3",
    "uuidStage": "stage3",
    "reasonForConsultation": "Adios",
    "desisted": 0
}

###
#Get de todos los casos de la tabla pac_case
GET {{host}}case/allcases
Content-Type: application/json

###
#Get en base al uuid de la persona
GET {{host}}case/viewcase/uuidcase3
Content-Type: application/json

###
#GET a todos los estados que puede tener una tabla
GET {{host}}stage/allstages
Content-Type: application/json

###
# Get a todos los campos de la tabla personuser
GET {{host}}/personuser
Content-Type: application/json

###
#GET a todos los campos de la tabla personpatient 
GET {{host}}/personpatient
Content-Type: application/json