@host = http://localhost:3000/person

###
POST {{host}}/create
Content-Type: application/json

{
    "firstName":"Mynor",
    "secondName":"marold",
    "lastName":3,
    "secondLastName":"",
    "marriedName":"jkl",
    "bornDate":"1997-11-23",
    "mobilePhone":"231232345",
    "email":"marold97@outlook.com"
}

###
GET {{host}}/2020-PSA25-00001
Content-Type: application/json

###
PUT {{host}}/2020-PSA25-00001
Content-Type: application/json

{
    "firstName":"mike",
    "secondName":"marold",
    "lastName":"castrillo",
    "secondLastName":"maldonado",
    "marriedName":"Mike",
    "bornDate":"1997-11-23",
    "mobilePhone":"231232345",
    "email":"marold97@hotlook.com"
}

###
DELETE {{host}}/2020-PSA24-00002

###
POST {{host}}/create
Content-Type: application/json

{

    "firstName":"", --NOT NULL
    "secondName":"Aroldo",
    "lastName":"Castrillo", --NOT NULL
    "secondLastName":"Maldonado",
    "marriedName":"",
    "bornDate":"1997-11-23", --NOT NULL
    "mobilePhone":"45720194",
    "email":"marold97@outlook.com",
    "uuidReligion":"001",

    "firstNameFather":"",
    "secondNameFather":"",
    "lastNameFather":"",
    "secondLastNameFather":"",
    "firstNameMother":"",
    "secondNameMother":"",
    "lastNameMother":"",
    "secondLastNameMother":"",
    "firstNameExtra":"",
    "secondNameExtra":"",
    "lastNameExtra":"",
    "secondLastNameExtra":"",

    "uuidAddress":"Jalapa", --NOT NULL
    "uuidCity":"001", --NOT NULL
    "addressLine1":"", --NOT NULL
    "addressLine2":"",
    "phoneNumber":"36079850",--NOT NULL

    "comment":"Ninguno al respecto",
    "attachment":"image.png"
}

###
call psicoapp.registerperson('0902', '2020-PSA-032', 'Danny', 'Rubilio', 'Castrillo', 
'Maldonado', '', '200-01-12', 'f773d0e2-6f64-4957-8ad4-179455994849', '2020-08-26',
 '45720194', 'marold@outlook.com', 'Miguel', 'Angel', 'Castrillo', 'López', 'Ana', 
 'Obdulia', 'Maldonado', 'Crúz', '', '', '', '', '001', '909', '2020-08-26', 
 'Ninguno al respecto',
 'http://image.jpg', '0014', '001', 'Jalapa, Jalapa', '', '23456789');