@host = http://localhost:3000/person

###
POST {{host}}/create
Content-Type: application/json

{
    "firstName":"Mynor",
    "secondName":"marold",
    "lastName":3,
    "secondLastName":"",
    "marriedName":"jkl",
    "bornDate":"1997-11-23",
    "mobilePhone":"231232345",
    "email":"marold97@outlook.com"
}

###
GET {{host}}/2020-PSA25-00001
Content-Type: application/json

###
PUT {{host}}/2020-PSA25-00001
Content-Type: application/json

{
    "firstName":"mike",
    "secondName":"marold",
    "lastName":"castrillo",
    "secondLastName":"maldonado",
    "marriedName":"Mike",
    "bornDate":"1997-11-23",
    "mobilePhone":"231232345",
    "email":"marold97@hotlook.com"
}

###
DELETE {{host}}/2020-PSA24-00002