@host = http://localhost:4000

POST {{host}}/therapeuticplan/create/uuid6
Content-Type: application/json

{
    "aspectToWork": "Escritura",
    "objetives": "Aprender a Escribir",
    "goals": "Que el niño escriba",
    "focus": "Introductorio",
    "techniques": "Aprestamiento"
}