@host = http://localhost:4000/psicoapp/v1/therapeuticplan

### Creacion de actividad del plan terapeutico
POST {{host}}/uuid6
Content-Type: application/json

{
        "aspectToWork": "Escritura",
        "aspectToWorkFile": "Escritura File",
        "objetives": "Aprender a Escribir", 
        "objetivesFile": "Aprender a Escribir File",
        "goals": "Que el niño escriba",
        "goalsFile": "Que el niño escriba File",
        "focus": "Introductorio",
        "focusFile": "Introductorio File",
        "techniques": "Aprestamiento",
        "techniquesFile": "Aprestamiento"
}

###
PUT {{host}}/uuid6/1d071545-66b3-4bdb-968e-688db9d24ef8
Content-Type: application/json

{
    "aspectToWork": "Escrituras"
}

###
GET {{host}}/getmany
Content-Type: application/json