@host = http://localhost:4000/psicoapp/v1/therapeuticplan

###
POST {{host}}/uuid6
Content-Type: application/json

{
    "aspectToWork": "Escritura",
    "objetives": "Aprender a Escribir",
    "goals": "Que el niño escriba",
    "focus": "Introductorio",
    "techniques": "Aprestamiento"
}

###
PUT {{host}}/uuid6/1d071545-66b3-4bdb-968e-688db9d24ef8
Content-Type: application/json

{
    "aspectToWork": "Escrituras"
}

###
GET {{host}}/getmany
Content-Type: application/json